### 1. 获取attri，不要列头，只取值

In [23]:
import pandas as pd
original_df = pd.read_csv("../original_df_2.csv")

In [24]:
del original_df['Unnamed: 0']

In [47]:
X = original_df.values.tolist()

In [51]:
len(X)

827565

### 2. 获取label，不要列头，只取值

In [29]:
import pandas as pd
df = pd.read_csv("../data/filter_time_data.txt", sep='\t\t', header=None)

/home/wujiaocan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  


In [30]:
df.columns = [ '电影ID','时间', '当前热度值', '新增热度值','当前点击量','新增点击量','当前评论数','新增评论数','当前点赞数','新增点赞数',
            '当前踩数','新增踩数','当前评分数','推广位','影片推广位等级','当前小时弹幕数','当前小时新增弹幕数','当前小时评分人数',
            '当前小时新增评分人数','当前小时五星评分人数','当前小时四星评分人数','当前小时三星评分人数','当前小时二星评分人数',
            '当前小时一星评分人数','当日爱奇艺播放指数','影片上线时间','导演','编剧','制片','美术','主演']

In [77]:
# df.tail(2).values

In [40]:
y_new_add_amount = df['新增点击量'].values.tolist()
y_total = df['当前点击量'].values.tolist()

In [42]:
# y_new_add_amount

In [45]:
# y_total

### 3. 按最佳参数训练

In [52]:
import xgboost as xgb
from xgboost import plot_importance
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split

# XGBoost训练过程
X_train, X_test, y_train, y_test = train_test_split(X, y_new_add_amount, test_size=0.2, random_state=0)

model = xgb.XGBRegressor(max_depth=7, n_estimators=500, gamma=0.027698143119166907, colsample_bytree=0.8957822073838446)
# model = xgb.XGBRegressor()
model.fit(X_train, y_train)

# 对测试集进行预测
ans = model.predict(X_test)

# 显示重要特征
plot_importance(model)
plt.show() 

<Figure size 640x480 with 1 Axes>

In [56]:
from sklearn import metrics

print("MSE:",metrics.mean_squared_error(y_test, ans))
print("RMSE:",np.sqrt(metrics.mean_squared_error(y_test, ans))) 

MSE: 2270612.4824847123
RMSE: 1506.855163074644


In [62]:
# model.fit(X_train, y_train)
model.save_model('y_new_add.model')  # 模型dump到本地

In [64]:
ans

array([  7.4724975, 792.6167   ,   3.0464313, ...,  12.388599 ,
        43.247227 ,  -5.936046 ], dtype=float32)

In [75]:
# y_test

In [71]:
tar = xgb.Booster(model_file='y_new_add.model')  # 加载模型
ans2 = tar.predict(xgb.DMatrix(X_test))   #预测模型

In [72]:
ans2

array([  7.4724975, 792.6167   ,   3.0464313, ...,  12.388599 ,
        43.247227 ,  -5.936046 ], dtype=float32)

In [78]:
import xgboost as xgb
from xgboost import plot_importance
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import metrics


# XGBoost训练过程
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X, y_total, test_size=0.2, random_state=0)

# model = xgb.XGBRegressor(max_depth=7, n_estimators=500, gamma=0.027698143119166907, colsample_bytree=0.8957822073838446)
model_2 = xgb.XGBRegressor()
model_2.fit(X_train_2, y_train_2)

# 下载模型
model_2.save_model('y_total.model')  # 模型dump到本地

# 对测试集进行预测
ans_2 = model_2.predict(X_test_2)

# 计算误差
print("MSE:",metrics.mean_squared_error(y_test_2, ans_2))
print("RMSE:",np.sqrt(metrics.mean_squared_error(y_test_2, ans_2))) 

# 显示重要特征
# plot_importance(model)
# plt.show() 

MSE: 2600102752040.9956
RMSE: 1612483.4114002525


In [79]:
tar = xgb.Booster(model_file='y_total.model')  # 加载模型
ans2 = tar.predict(xgb.DMatrix(X_test))   #预测模型

In [80]:
ans2

array([ 1287425.8 , 39716172.  ,   307116.5 , ...,  2495107.  ,
         314774.88,  1214898.6 ], dtype=float32)

In [128]:
len(np.array([1,2,3,4]).shape)

1

In [85]:
aa

array([1, 2, 3, 4])

In [91]:
aa[np.newaxis, :]

array([[1, 2, 3, 4]])

In [92]:
abc = [1,2,3,4]

In [106]:
def if_need_transfer(data):
    try:
        if np.array(data).shape[1]:
            return False
    except Exception as e:
        return True

In [117]:
transfer_demission(abc, if_need_transfer(abc))

[[1, 2, 3, 4]]

In [116]:
def transfer_demission(data, flag):
    if flag == True:
        return np.array(data)[np.newaxis, :].tolist()
    if flag == False:
        return data

In [111]:
# transfer_demission(abc, True)

In [121]:
aabbcc = [[[1,2,3,4],
          [2,3,4,5],
          [3,4,5,6]]]

In [125]:
len(np.array(aabbcc).shape)

3

In [129]:
def transfer_demission(data):
    # 输入的是一维数据，转成2维
    if len(np.array(data).shape) == 1:
        return np.array(data)[np.newaxis, :].tolist()
    # 输入的是二维数据，正常输出
    if len(np.array(data).shape) == 2:
        return data
    # 输入的是多维数据，报错
    if len(np.array(data).shape) > 2:
        print("输入数据维度过高，请转成二维！")

In [137]:
aaa = transfer_demission([54062, '2018-10-11 18:00:00', 845.0, 0.0, 0.0, 0.0, 1791.0, 0.0,
      36173.0, 0.0, 443.0, 0.0, 760.0, '无', 'a', 5563.0, 0.0, 428083.0,
      0.0, 258640.0, 93910.0, 39379.0, 11496.0, 24658.0, -111111111.0,
      '2018-05-15 15:30:12', '郎贵钧', '张帅,杨勐', '张晋,晋铨', np.nan,
      '卢冠东,李龙,王军,李玉龙'])

In [149]:
# for i in aaa[0]:
#     if "." in i:
#         i = float(i)

In [148]:
# aaa[0]

In [131]:
transfer_demission([[1,2,3,4,5]])

[[1, 2, 3, 4, 5]]

In [132]:
transfer_demission([[[1,2,3,4,5,6]]])

输入数据维度过高，请转成二维！


In [134]:
a = [54062, '2018-10-11 18:00:00']

In [136]:
np.array(a)[np.newaxis, :]

array([['54062', '2018-10-11 18:00:00']], dtype='<U21')

In [257]:
all_data = pd.read_csv("../data/all_data.txt", sep="\t\t", header=None)

/home/wujiaocan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.


In [277]:
# all_data.iloc[9990:9991, : ].values.tolist()

In [278]:
all_data.columns = [ '电影ID','时间', '当前热度值', '新增热度值','当前点击量','新增点击量','当前评论数','新增评论数','当前点赞数','新增点赞数',
            '当前踩数','新增踩数','当前评分数','推广位','影片推广位等级','当前小时弹幕数','当前小时新增弹幕数','当前小时评分人数',
            '当前小时新增评分人数','当前小时五星评分人数','当前小时四星评分人数','当前小时三星评分人数','当前小时二星评分人数',
            '当前小时一星评分人数','当日爱奇艺播放指数','影片上线时间','导演','编剧','制片','美术','主演']

In [279]:
# 时间格式为日期+时间戳，将特征“时间”转成新的特征“hour”
def get_date(x):
    return x.split()[0]

def get_hour(x):
    return x.split()[1].split(":")[0]

In [280]:
all_data["date"] = all_data["时间"].apply(get_date)

In [281]:
import datetime

In [282]:
def get_movie_data_in_daterange(data, date_range, movie_id):
    '''
        获取一定时间范围内，某部电影的数据
    '''
    weekday = []
    for i in date_range:
        weekday.append(data[(data['date'] == i) & (data['电影ID'] == movie_id)])
    return weekday

In [283]:
def get_dateRange(beginDate, endDate):
    '''
    :param beginDate: 时间范围开始的日期
    :param endDate: 时间范围结束的日期
    :return: 该时间范围内的时间序列
    '''
    dates = []
    dt = datetime.datetime.strptime(beginDate, "%Y-%m-%d")
    date = beginDate[:]
    while date <= endDate:
        dates.append(date)
        dt = dt + datetime.timedelta(1)
        date = dt.strftime("%Y-%m-%d")
    return dates

In [284]:
get_movie_data_in_daterange(all_data, get_dateRange("2018-09-26", "2018-09-28"), 33638)[0].to_csv("./new_data.csv")

In [285]:
get_movie_data_in_daterange(all_data, get_dateRange("2018-09-26", "2018-09-28"), 33638)[1].to_csv("./new_data.csv", mode='a', header=None)
get_movie_data_in_daterange(all_data, get_dateRange("2018-09-26", "2018-09-28"), 33638)[2].to_csv("./new_data.csv", mode='a', header=None)

In [286]:
new_data = pd.read_csv("./new_data.csv", index_col=0)

In [287]:
del new_data['date']

In [289]:
# new_data

In [290]:
new_data.to_csv("./new_data.csv")

In [254]:
dddd = pd.read_csv("./new_data.csv", index_col=0)

In [296]:
# dddd.iloc[10:11, :].values.tolist()

In [240]:
dddd = pd.read_csv("./new_data.csv", index_col=0)

电影ID                   时间   当前热度值  新增热度值  当前点击量  新增点击量  当前评论数  新增评论数  \
2918    15  2018-09-26 00:00:00  1611.0    0.0    0.0    0.0  108.0    0.0   
2919    15  2018-09-26 01:00:00  1611.0    0.0    0.0    0.0  108.0    0.0   

      当前点赞数  新增点赞数        ...         当前小时三星评分人数  当前小时二星评分人数  当前小时一星评分人数  \
2918  831.0    0.0        ...              443.0       434.0       573.0   
2919  831.0    0.0        ...              443.0       434.0       573.0   

     当日爱奇艺播放指数               影片上线时间       导演  编剧             制片  美术  \
2918     115.0  2017-04-28 15:30:24  李奇龙,田泽姚 NaN  李康,严国豪,徐亮,林彦君 NaN   
2919     115.0  2017-04-28 15:30:24  李奇龙,田泽姚 NaN  李康,严国豪,徐亮,林彦君 NaN   

                    主演  
2918  李奇龙,苏拉文雅,田泽姚,刘金金  
2919  李奇龙,苏拉文雅,田泽姚,刘金金  

[2 rows x 31 columns]

In [222]:
# new_data.values.tolist()